---
- name: stop wordpress
  hosts: all
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: Remove wordpress container
      docker_container:
        name: wordpress
        state: absent
      tags: stop-wordpress

    - name: Remove database container
      docker_container:
        name: db
        state: absent
      tags: stop-wordpress
