---
- name: start nginx container
  hosts: all
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: Launch the nginx container
      docker_container:
        name: nginx
        image: nginx
        ports:
          - 8180:80
      tags: start-nginx
