---
- name: start wordpress
  hosts: all
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: Launch database container
      docker_container:
        name: db
        image: mariadb
        env:
          MYSQL_ROOT_PASSWORD: example
      tags: start-wordpress

    - name: Launch wordpress container
      docker_container:
        name: wordpress
        image: wordpress
        links:
        - db:mysql
        ports:
        - 8080:80
      tags: start-wordpress
